# Generated by Django 5.0 on 2024-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_discount_product_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="product",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="product",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Modified At"
            ),
        ),
    ]
