# Generated by Django 5.0 on 2024-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="starting_from",
            field=models.DateTimeField(
                null=True, verbose_name="Starting From"
            ),
        ),
    ]
