# Generated by Django 5.0 on 2024-06-02 04:58

import datetime_validators.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_discount_starting_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="discount",
        ),
        migrations.AddField(
            model_name="discount",
            name="product",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="discount",
            name="ending_at",
            field=models.DateTimeField(
                null=True,
                validators=[
                    datetime_validators.validators.date_time_is_future_validator
                ],
                verbose_name="Ending At",
            ),
        ),
    ]
